import { describe, it, expect } from "vitest";
import { parseCycleFile, tokenBar, formatK, deltaLabel } from "./layers.js";

// ---------------------------------------------------------------------------
// formatK
// ---------------------------------------------------------------------------

describe("formatK", () => {
  it("returns plain number for values under 1000", () => {
    expect(formatK(999)).toBe("999");
    expect(formatK(0)).toBe("0");
  });

  it("formats 1000 as 1.0K", () => {
    expect(formatK(1000)).toBe("1.0K");
  });

  it("formats 1500 as 1.5K", () => {
    expect(formatK(1500)).toBe("1.5K");
  });

  it("formats large numbers", () => {
    expect(formatK(10000)).toBe("10.0K");
  });
});

// ---------------------------------------------------------------------------
// tokenBar
// ---------------------------------------------------------------------------

describe("tokenBar", () => {
  it("contains exactly 16 bar characters between delimiters", () => {
    const bar = tokenBar(500, 1000);
    // Strip ANSI escape codes, then count characters between ▕ and ▏
    const stripped = bar.replace(/\x1b\[[0-9;]*m/g, "");
    const inner = stripped.slice(1, -1); // remove ▕ and ▏
    expect(inner.length).toBe(16);
  });

  it("fills all bars when avgTokens equals maxTokens", () => {
    const bar = tokenBar(1000, 1000);
    const stripped = bar.replace(/\x1b\[[0-9;]*m/g, "");
    const inner = stripped.slice(1, -1);
    expect(inner).toBe("█".repeat(16));
  });

  it("fills at least 1 bar when avgTokens is 0", () => {
    // Math.max(1, 0) → 1 filled bar
    const bar = tokenBar(0, 1000);
    const stripped = bar.replace(/\x1b\[[0-9;]*m/g, "");
    const inner = stripped.slice(1, -1);
    expect(inner[0]).toBe("█");
  });
});

// ---------------------------------------------------------------------------
// deltaLabel
// ---------------------------------------------------------------------------

describe("deltaLabel", () => {
  it("returns empty string when values are equal", () => {
    expect(deltaLabel(500, 500)).toBe("");
  });

  it("contains ↓ when current is less than prior (improvement)", () => {
    const label = deltaLabel(400, 500);
    // Strip ANSI
    const stripped = label.replace(/\x1b\[[0-9;]*m/g, "");
    expect(stripped).toContain("↓");
    expect(stripped).toContain("20%"); // (500-400)/500 * 100 = 20%
  });

  it("contains ↑ when current is greater than prior (regression)", () => {
    const label = deltaLabel(600, 500);
    const stripped = label.replace(/\x1b\[[0-9;]*m/g, "");
    expect(stripped).toContain("↑");
    expect(stripped).toContain("20%");
  });

  it("returns empty string for very small difference rounding to 0%", () => {
    // 1/1000 = 0.1% rounds to 0
    expect(deltaLabel(1001, 1000)).toBe("");
  });
});

// ---------------------------------------------------------------------------
// parseCycleFile
// ---------------------------------------------------------------------------

const SAMPLE_CYCLE = `# Retro Cycle — 2025-03-15

> Generated by \`patina run\` on 2025-03-15T12:00:00Z
> Cycle period: 2025-03-01 → 2025-03-15
> Sessions analysed: 8

---

## Metrics Snapshot

| Metric | Value |
|---|---|
| Total sessions | 8 |
| Total tokens (est.) | 48,000 |
| Avg tokens/session | 6,000 |
| Sessions with rework | 2 (25.0%) |

---

## Cycle Summary

This cycle showed consistent progress on the core feature set.

---

## Proposed Instruction Change

**Section:** 1. Working Agreements
`;

const ONBOARDING_CYCLE = `# Onboarding Cycle — 2025-01-01

> Generated by \`patina run\` (first cycle setup) on 2025-01-01T00:00:00Z

---

## Summary

${`(first cycle setup)`} — established initial working agreements.
`;

describe("parseCycleFile", () => {
  it("parses session count from metrics table", () => {
    const layer = parseCycleFile(SAMPLE_CYCLE, "2025-03-15");
    expect(layer.sessions).toBe(8);
  });

  it("parses avg tokens (with comma formatting)", () => {
    const layer = parseCycleFile(SAMPLE_CYCLE, "2025-03-15");
    expect(layer.avgTokens).toBe(6000);
  });

  it("parses rework percentage", () => {
    const layer = parseCycleFile(SAMPLE_CYCLE, "2025-03-15");
    expect(layer.reworkPct).toBe(25.0);
  });

  it("truncates summary longer than 72 characters", () => {
    const longSummary = "a".repeat(80);
    const doc = `## Cycle Summary\n\n${longSummary}\n`;
    const layer = parseCycleFile(doc, "2025-01-01");
    expect(layer.summary.length).toBeLessThanOrEqual(73); // 72 + '…'
    expect(layer.summary.endsWith("…")).toBe(true);
  });

  it("does not truncate summary of exactly 72 characters", () => {
    const exactSummary = "b".repeat(72);
    const doc = `## Cycle Summary\n\n${exactSummary}\n`;
    const layer = parseCycleFile(doc, "2025-01-01");
    expect(layer.summary).toBe(exactSummary);
  });

  it("returns isOnboarding true for onboarding cycle files", () => {
    const layer = parseCycleFile(ONBOARDING_CYCLE, "2025-01-01");
    expect(layer.isOnboarding).toBe(true);
  });

  it("returns isOnboarding false for regular cycle files", () => {
    const layer = parseCycleFile(SAMPLE_CYCLE, "2025-03-15");
    expect(layer.isOnboarding).toBe(false);
  });

  it("returns undefined for missing fields in a minimal file", () => {
    const layer = parseCycleFile("# Empty cycle\n", "2025-01-01");
    expect(layer.sessions).toBeUndefined();
    expect(layer.avgTokens).toBeUndefined();
    expect(layer.reworkPct).toBeUndefined();
    expect(layer.summary).toBe("");
  });

  it("sets the date field from the parameter", () => {
    const layer = parseCycleFile(SAMPLE_CYCLE, "2025-03-15");
    expect(layer.date).toBe("2025-03-15");
  });
});
